audit_header: false
title: DC Metro's Best Real Estate Training
description: >-
  Jeff Wheatley, a top Real Estate Agent in The DC Metro, shares his own
  internal real estate agent training for free. His Real Estate Training, Tips
  and Advice will help you sell more homes in less time.
show_custom_links: true
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: 'https://www.eventbrite.com/o/wheatley-group-at-keller-williams-18160937865'
  - title: Free Strategy Call
    url: /strategy-call/
  - title: Free Newsletter
    url: /subscribe/
client:
  name: Jeff Wheatley
  title:
  license_number:
  about_markdown: >-
    Jeff Wheatley is passionate about serving his clients transform their lives
    through real estate. His extensive background in real estate, finance, and
    life coaching enables him to draw from a deep well of life experience as he
    helps his clients make long term, intelligent decisions. In a shifting real
    estate market and changing landscape, his expertise and and focus on long
    terms goals provide a rare breed of service.


    Described by his peers and clients as smart, insightful and determined, Jeff
    goes beyond expectations in serving his clients. Jeff has has re-engineered
    the home seller process. He modeled his process after the best marketing
    practices in all industries. As a specific example, Jeff’s team launches a
    property through a carefully curated process with similarities to Apple’s
    launch process. His process builds anticipation and desire similar to the
    launch of iPhone 10XS. Contrast that to the last majority of his competition
    simple list a property by simply pray it sells.
  market: DC Metro
  brand: The Wheatley Group
  brokerage: Re/Max Realty Services
  address: '20 West Gude Drive #200<br>Rockville Md. 20850'
  phone: 240-731-7578
  phone_type: Direct
  phone2: 301-251-1221
  phone2_type: Office
  email: Jeff@JeffWheatleyHomes.com
  url: 'http://www.JeffWheatleyHomes.com'
lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: 'http://fillmurray.com/200/200'
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: 'http://eyegoop.com'
socials:
  review_sm_icons: false
  facebook_url: 'https://www.facebook.com/KWCPRockville'
  linkedin_url: 'https://www.linkedin.com/in/jeffreywheatley/'
  gplus_url:
  youtube_url: 'https://www.youtube.com/channel/UCZR38Rvd7jWmmow5G7DdtPg'
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:
podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories:
    - Education
  image: /img/podcast.jpg
  subtitle: >-
    Learn all the tips, tricks and more for buyers and sellers in the -- MARKET
    -- Area Real Estate Market
  description: >-
    If you are looking to buy or sell a home, get all the information and the
    latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional
    -- MARKET -- Real Estate Agents.
  keywords: >-
    Real Estate for sale, Real Estate agents, top real estate agents, local real
    estate agents, find a real estate agent, houses for sale in -- MARKET --,
    home selling tips, home for sale, home buying, home buying process, property
    finder, property search, property, real estate market, estate agent,
    realestate, real estate listings, buying a house, homes for sale, mls, home
    buyer
  author: '-- CLIENT NAME --'
images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 50
  hero_text: '-- MARKET -- Real Estate Video Blog'
  hero_background_hex: '#999999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#b40101'
  theme_color: '#999999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'
navbar_colors:
  border_bottom:
header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: 'rgba(0, 0, 0, 0)'
buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: 'rgba(0, 0, 0, 0)'
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'